### ISSUE TITLE
Cannot test bgp

### ISSUE THREAD

**Issue by igoqueen5** [CiscoTestAutomation/solutions_examples#1]
Hi, thanks open this issue.

I have tried to solution_examples/bgp_adjacencies's tutorial but I got this error message below.
'''
LookupError: No such attribute in abstraction package 'genie.libs.ops': 'genie.libs.ops.bgp.bgp.Bgp'
'''
I have checked my testbed and bgp status but these are fine. I have also tried to Ping module from pyATS and that works fine.

Or accordingly this error message, probably I don't install pyATS and Genie module correctly?

**Comment by jeaubin** [comment]
Hi, 

in your yaml file,  what is the OS you are using ? The error you are showing seems to come from our abstraction package looking for a specific os which we dont have the library yet.

https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/models/bgp

Click on Operation;

https://github.com/CiscoTestAutomation/genielibs/tree/master/pkgs/ops-pkg/src/genie/libs//ops/bgp 

However if you are wanting IOS,  you can most likely switch your os to iosxe in the testbed yaml file  and we've seen case where it would work, as they are so similar for show command.

**Comment by igoqueen5** [comment]
@jeaubin Thank you for answering. I was test it for cisco ios router.
 I have rewrite testbed file to change os type as iosxe then execute but got error message 'Failed reason: Testbed has BGP Neighbors that are not established'. But now is that working correctly?

**Comment by siming85** [comment]
(uploading what @igoqueen5 emailed)

[error_log.txt](https://github.com/CiscoTestAutomation/solutions_examples/files/3085037/error_log.txt)

**Comment by karmoham** [comment]
Hi Lisa @igoqueen5 

An enhancement has been pushed to the repo, let us know if that works so we go ahead and close the ticket.

Thank you,
Karim

**Comment by igoqueen5** [comment]
The BGP_Neighbors_Established.py had some bugs so that's why my 
BGP test could not works correctly.
Genie support team fix this bug as below so I close this issue.  Thanks!
https://github.com/CiscoTestAutomation/solutions_examples/blob/master/bgp_adjacencies/BGP_Neighbors_Established.py
