### ISSUE TITLE
position of " failed_dict[device] = {} "

### ISSUE THREAD

**Issue by zkzqzk** [CiscoTestAutomation/solutions_examples#19]
line 106 -- " failed_dict[device] = {} "

Is above line  to initiate  the dict to store the failed neighbor for a device at the right place?   It seems to me if needs to be in the device loop, not in the neighbor loop.  Because if it is neighbor loop,  it will become empty every time there is a  failed neighbor, so only the last failed neighbor will be stored.  Correct me if I am wrong.

Thanks,

Ken

**Comment by LenzDong** [comment]
Hi, 

You can initiate the dict outside the for loop:
```
failed_dict = {}

for device in dev_list:
      failed_dict[device.name] = {}

Thanks,
