### ISSUE TITLE
Missing topology.virl? 

### ISSUE THREAD

**Issue by ericchou1** [CiscoTestAutomation/solutions_examples#20]
Hi, the README file mentioned a topology.virl file that can be used with the solutions. Is it still available? Thank you. 

https://github.com/CiscoTestAutomation/solutions_examples/blob/master/topology.virl

**Comment by ericchou1** [comment]
Oh, I see that all but the atest_examples jobs were pointing to the [default_testbed.yaml | devnet_sandbox.yaml] that points to these two devices: 
[ios-xe-mgmt.cisco.com] https://devnetsandbox.cisco.com/RM/Diagram/Index/27d9747a-db48-4565-8d44-df318fce37ad?diagramType=Topology
[sbx-nxos-mgmt.cisco.com] https://devnetsandbox.cisco.com/RM/Diagram/Index/dae38dd8-e8ee-4d7c-a21c-6036bed7a804?diagramType=Topology

If confirmed, happy to close this comment or update & PR for the readme file if you'd like. Thank you!

**Comment by ahersi2-cisco** [comment]
Hi Eric,

Sorry for the late response. We have some example virl files on this page that might be of help;

https://pubhub.devnetcloud.com/media/genie-docs/docs/userguide/examples/virl.html#

If you don't mind making a PR for this comment, we can close this comment. Thank you.

**Comment by ericchou1** [comment]
Hi @ahersi2-cisco, thank you for the response, I find the VIRL file useful. Per suggestion, I have created a PR for the README file, https://github.com/CiscoTestAutomation/solutions_examples/pull/21. I will consider this issue resolved and close this comment. Thanks again!
